FROM nginx:alpine
LABEL author="Matthew Sessions"
COPY ./build /var/www/
COPY default-prod.conf /etc/nginx/nginx.conf
COPY /ssl/ /etc/nginx/ssl
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["nginx","-g","daemon off;"]